### PR TITLE
feat(project.clone): add option to preserve namespaces by subdirectories

### PR DESCRIPTION
**Pull request by loupgaroublond**
**Description**

**Related Issue**

Resolves #[issue_number]

**How Has This Been Tested?**

**Screenshots (if appropriate):**

**Types of changes**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation
- [ ] Chore (Related to CI or Packaging to platforms)

### CODE REVIEW

**Comment by zemzale** [comment]
Thanks, for the PR @loupgaroublond 
We generally don't accept PRs without an issue attached to them, but this seems, like a nice feature, and does work as expected.

If @profclems is up for this I believe this can be merged into trunk

**Comment by loupgaroublond** [comment]
If you folks can take this as is, that is excellent. Otherwise, happy to open up an issue and go through the change more. There were definitely a few behavioral choices I made unilaterally, that, both, I'd like to change, and I bet others have Strong Opinions on too.

If nothing else, we needed this change at work - so here's the change, it'll get active use off my fork, and whenever you're ready, we can merge it back in.

**Comment by profclems** [comment]
Thanks for working on this @loupgaroublond 

@zemzale you may review and merge if you have some time on your hands right now

**Review by profclems — COMMENTED** [review]
@loupgaroublond thanks for working on this! It's a really nice feature.
I'm having a few thoughts on the naming of the `--preserve-namespace | p` flag. 

@zemzale @maxice8 should we maintain that flag name?

**Review by zemzale — COMMENTED** [review]
I don't have a better idea for `preserve-namespace`, name, but we might go without the `p` short flag maybe? I don't think that this flag is such a common thing, and there are already a lot of instances of `p` mostly meaning `page` for list requests.

**Comment by zemzale** [comment]
This also works with nested groups, 
image
Turns into 
image

Not counting the nitpick about the short flag LGTM.

**Review by zemzale — APPROVED** [review]

**Comment by loupgaroublond** [comment]
> I don't have a better idea for `preserve-namespace`, name, but we might go without the `p` short flag maybe? I don't think that this flag is such a common thing, and there are already a lot of instances of `p` mostly meaning `page` for list requests.

I am ok with dropping the short flag. Please stay tuned for a patch to the PR.

**Comment by loupgaroublond** [comment]
> This also works with nested groups,
> image
> Turns into
> image
> 
> Not counting the nitpick about the short flag LGTM.

Those nested groups is entirely the motivating use case for me here :)

**Review by profclems — APPROVED** [review]
On second thought, we can still maintain the `-p` shorthand for the `--preserve-namespace` flag since this isn't a `list` command

Thanks a lot @loupgaroublond for working on this... It will be released as part of v1.16.0

**Pull request merged**
