### PR TITLE
added dynamic completion

### LINKED ISSUE #724: dynamic completion
Added basic dynamic completion: https://github.com/rsteube/glab

[asciicast](https://asciinema.org/a/414156)

related #174

### PR DESCRIPTION
**Pull request by rsteube**
**Description**
Added dynamic completion using [carapace](https://github.com/rsteube/carapace). 

**Related Issue**
Resolves #724

**How Has This Been Tested?**
Testing is still limited and i expect some small issues regaring the values being completed (e.g it seems the repo clone command currently ignores the host prefix and tries to use `gitlab.com`).
There might also be some small issues regarding different environments (os/shell) regarding carapace itself - works fine in tests and there haven't been any issues with [lab](https://github.com/zaquestion/lab) so far though.
Personally using [elvish](https://elv.sh/) on linux.
Does not affect current completion provided by cobra itself, so these can be used in parallel.

**Screenshots (if appropriate):**
[asciicast](https://asciinema.org/a/414156)

**Types of changes**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation
- [ ] Chore (Related to CI or Packaging to platforms)

**Usage**
```sh
#bash
source <(glab _carapace)

# elvish
eval (glab _carapace|slurp)

# fish
glab _carapace | source

# oil
source <(glab _carapace)

# powershell
Set-PSReadlineKeyHandler -Key Tab -Function MenuComplete
glab _carapace | Out-String | Invoke-Expression

# xonsh
COMPLETIONS_CONFIRM=True
exec($(glab _carapace))

# zsh
source <(glab _carapace)
```

### CODE REVIEW

**Comment by profclems** [comment]
@rsteube thanks for working on this... This is a great feature. But since this is huge PR with a lot of changes, I would request for your patience while we review this PR. 
Thanks again!

**Comment by rsteube** [comment]
@profclems Yeah, might be better to split this up. Btw. it's also possible to implement this as external completer (separate binary) so that glab won't be entangled with carapace.

**Review by zemzale — COMMENTED** [review]
I skimmed through this and I didn't see anything really wrong with the PR, but it's really huge and there are probably are some issues I just don't see. If we could add command by command it would be a lot easier to review and test.

**Comment by profclems** [comment]
@rsteube Great thanks for all this work. 

I believe there are lots of things to take into consideration and **caching** is the major thing. For now, this is API-backed and this will hit the API repeatedly and that's something to be avoided.

Also as we know it, vanilla bash does not support descriptions out of the box so it would be ideal for users on richer shells like zsh, fish, elvish etc.

> Btw. it's also possible to implement this as external completer (separate binary) so that glab won't be entangled with carapace.

I agree with this! So it would be an option for users who actually need it. We can give it a spot on our readme with description on where to find it, how to install and use it.

Great thanks for all this!

**Comment by rsteube** [comment]
@profclems Alright, i'll give you a heads up again when i moved things around.

**Comment by rsteube** [comment]
@profclems moved it [here](https://github.com/rsteube/carapace-bin/tree/master/completers/glab_completer/cmd)

**Pull request closed without merging**
