### PR TITLE
feat: Add release command

### PR DESCRIPTION
**Pull request by pgollangi**
- Define release base command
- Add release list command

**How Has This Been Tested?**

**Screenshots (if appropriate):**

**Types of changes**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

**Checklist:**

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by profclems — COMMENTED** [review]
Great!
Do you have plans of adding commands to create a release in your free time??

**Comment by pgollangi** [comment]
Haha yes, ofcourse @profclems

**Comment by profclems** [comment]
> Haha yes, ofcourse @profclems

Haha... good work

**Comment by profclems** [comment]
Do you want this PR merged while you work on the others or after you're done?

**Comment by pgollangi** [comment]
@profclems I would like to incrementally complete it. Please merge this PR to avoid rework in case of structural changes happening across all commands. I will raise a separate PR for remaining work.

**Comment by profclems** [comment]
@all-contributors please add @pgollangi  for code

**Comment by profclems** [comment]
@all-contributors please add @pgollangi for code

**Pull request merged**
