### PR TITLE
chore: add alpine package support

### LINKED ISSUE #331: Alpine Linux Packaging
Most CI environments like to use alpine Linux for its lightweight nature.
It would be nice to have `glab` packaged in the official alpine package repository so it can be installed with:
```sh
$ apk add glab
```
In the meantime, you can easily install with the [quick install script](https://github.com/profclems/glab/blob/trunk/scripts/quick_install.sh) via curl or wget as stated in the [readme](https://github.com/profclems/glab#quick-install-bash)
```
$ curl -sL https://j.mp/glab-i | sudo bash
```
I would like to do it but I'm no alpine packaging expert 🤗. 
It is however, open for anyone who would like to help with the packaging

### PR DESCRIPTION
**Pull request by solidnerd**
**Description**
Add alpine package support.

**Related Issue**

Resolves #331 

**How Has This Been Tested?**

Starting a docker container with alpine and add the testing repo for fetching glab

```
docker run -it --rm alpine:3.12
> echo "@testing http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
> apk add --no-cache glab@testing
```

**Final Output:** 
```
> apk add --no-cache glab@testing
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
(1/1) Installing glab@testing (1.12.1-r0)
Executing busybox-1.31.1-r19.trigger
OK: 26 MiB in 15 packages
```

**Screenshots (if appropriate):**

image

**Types of changes**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation
- [x] Chore (Related to CI or Packaging to platforms)

### CODE REVIEW

**Comment by solidnerd** [comment]
@profclems  Here we go 💯

**Comment by maxice8** [comment]
I believe `glab` is ready for inclusion into community (so it is available in 3.13)

**Comment by maxice8** [comment]
https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/16107

**Comment by profclems** [comment]
@maxice8 I think we can merge this one while we wait for the new MR (move to community repo) to be merged.

My concern is: will the move affect users who initially installed `glab` from the testing repo?

**Comment by solidnerd** [comment]
@profclems @maxice8 

I assume that they won't receive any updates anymore. This was my intention to use a [repository pinning](https://wiki.alpinelinux.org/wiki/Alpine_Linux_package_management#Repository_pinning) to be sure that nothing breaks for the existing user. But everyone should keep in mind they are using the **edge branch**  so there could be breaking changes and also the same that they are using the **testing repository.**

> After which you can "pin" dependencies to these tags using:

> `apk add glab@testing` 
> Apk will now by default only use the untagged repositories, but adding a tag to specific package:

> 1. will prefer the repository with that tag for the named package, even if a later version of the package is available in another repository

> 2. allows pulling in dependencies for the tagged package from the tagged repository (though it prefers to use untagged repositories to satisfy dependencies if possible

We are in a lucky position because every 6 months a new release will happen what the snapshot of the `edge` repository is. Because we are at the end of the year. It will be included in 3.13. See [Release Notes](https://wiki.alpinelinux.org/wiki/Alpine_Linux:Releases)

## What are the next steps?

I would also be fine to write later the migration guide on how to move from the testing repository to the community repository.

**Review by profclems — APPROVED** [review]

**Comment by maxice8** [comment]
> My concern is: will the move affect users who initially installed glab from the testing repo?

Depends on the user.

Alpine Edge users (those that use main + community + testing) will be upgraded to the community package if they do `apk upgrade -a` or whenever there is a new version.

Those that use stable but pin won't receive updates because the package is no longer in the testing repo and they don't have the edge/community repository.

**Comment by solidnerd** [comment]
@profclems @maxice8  I updated the readme. It's already in the community repo 😄 . I also added a note about using edge and how to use it in a Dockerfile.

If something is missing, let me know.

**Comment by profclems** [comment]
That was fast! Funny how I was typing a review and was prompted the diff is outdated. 😂

**Review by profclems — COMMENTED** [review]
That was fast! Funny how I was typing a review and was prompted the diff is outdated. 

I'll submit it anyway 🤣

**Review by profclems — COMMENTED** [review]
That's an expressive instruction you've added 🎉. Good job @solidnerd. Thanks a lot.

We should add the alpine to the table of contents. The TOC is there for those who wouldn't want to scroll through the README looking for one particular topic :()

```md
* [Usage](#usage)
   * [Core Commands](#core-commands)
   * [Additional Commands](#additional-commands)
   * [Examples](#examples)
* [Demo](#demo)
* [Learn More](#learn-more)
* [Installation](#installation)
   * [Quick Install (Bash)](#quick-install-bash)
   * [Windows](#windows)
      * [WinGet](#winget)
      * [Scoop](#scoop)
      * [EXE Installer](#exe-installer)
   * [Linux](#linux)
      * [Linuxbrew (Homebrew)](#linuxbrew-homebrew)
      * [Snapcraft](#snapcraft)
      * [Arch Linux](#arch-linux)
      * [KISS Linux](#kiss-linux)
      * [Alpine Linux](#alpine-linux)
         * [Install a pinned version from edge](#install-a-pinned-version-from-edge)
         * [Alpine Linux Docker-way](#alpine-linux-docker-way)
   * [MacOS](#macos)
      * [Homebrew](#homebrew)
   * [Building From Source](#building-from-source)
      * [Prerequisites](#prerequisites-for-building-from-source-are)
* [Authentication](#authentication)
* [Configuration](#configuration)
* [Environment Variables](#environment-variables)
* [Issues](#issues)
* [Contributing](#contributing)
   * [Support glab <g-emoji class="g-emoji" alias="sparkling_heart" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f496.png">💖</g-emoji>](#support-glab-)
      * [Individuals](#individuals)
      * [Backers](#backers)
* [License](#license)
```

**Review by profclems — APPROVED** [review]

**Pull request merged**
