### PR TITLE
feat: Add aliases for long commands

### LINKED ISSUE #108: Add aliases for long commands
**Is your feature request related to a problem? Please describe.**
It would be nice if a user could create aliases for long commands that they use a lot.

**Describe the solution you'd like**
The [GitHub CLI](https://cli.github.com/manual/gh_alias_set) handles aliases very nicely, so it may be a good idea to base it off of their approach. The key features include:
- Ability to list aliases
- Ability to add an alias
- Ability to delete an alias

Aliases should allow for insertion of arguments into their longer form. One way to do this would be a shell-style syntax such as:
```
glab alias set createissue 'glab issue create --title "$1" --description "$2"'
```
When the alias is used:
```
glab createissue "My Issue" "Something is broken."
```
It should be executed as:
```
glab issue create --title "My Issue" --description "Something is broken."
```

*Note: It is important that the user should be able to escape the dollar character (or whatever is used to indicate insertion). It is also important that the escape character can be escaped!*

**Describe alternatives you've considered**
Predefined aliases are nice (such as `glab issue create`/`glab issue new` being the same), but giving the user flexibility to create their own is much better.

### PR DESCRIPTION
**Pull request by BreD1810**
**Description**

It would be nice if a user could create aliases for long commands that they use a lot. The changes made will be based upon the [GitHub CLI](https://cli.github.com/manual/gh_alias_set) format.

**Related Issue**
#108 

**Motivation and Context**
This makes long commands easier to use.

**How Has This Been Tested?**
See screenshot below:
image

**Screenshots (if appropriate):**

**Types of changes**
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

**Checklist:**
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by profclems** [comment]
@all-contributors please add @BreD1810  for code, platform and documentation

**Comment by BreD1810** [comment]
I'm not really sure where to go from here :/. I've had a look at the way the GitHub CLI implements executing aliases. Unfortunately, I am quite new to Golang, and very new to cobra, so I haven't managed to work it out yet.
Any suggestions are appreciated!

**Comment by profclems** [comment]
I've been following your commits and I can say you started out really well. 
We can save the aliases in a separate file (aliases.format) in the global config directory and map the aliased command to its corresponding key value.

**Comment by profclems** [comment]
Great implementation @BreD1810 
Works as expected 🎉

I will write unit tests for it

**Pull request merged**
