### PR TITLE
Add more tests, use `pkg/prompt` for prompts

### PR DESCRIPTION
**Pull request by maxice8**
**Description**

Add tests for `BaseRepo()` and `HeadRepo()`

### CODE REVIEW

**Review by profclems — APPROVED** [review]
LGTM! Thanks a lot

**Comment by maxice8** [comment]
@profclems Is there a way to enable `group` codecov bots in this repository ?

I think with the current case only you get a `codecov-bot` comment instead of every users

**Comment by profclems** [comment]
The test runs in GitLab CI but GitLab CI does not run for forks. To fix this, I did a workaround where @clemsbot creates a new branch for each PR on the GitLab mirror so the CI runs and reports back. Though the test report is sent to codecov, codecov is unable to detect the actual branch from which the PR is created from.

So to resolve this, you would have to work directly on `profclems/glab` instead of your fork

**Comment by profclems** [comment]
I'm thinking of removing the test job from the GitLab CI and run it in GitHub action or Travis CI

**Comment by maxice8** [comment]
I think it would be nice to have it as a GitHub action

**Comment by profclems** [comment]
Yeah I will open a PR right away

**Pull request merged**
