### PR TITLE
feat: Issue link on create

### LINKED ISSUE #351: Enable issue linking for issue creation
We can link MR's to an issue, but we are not able to link related issues through the cli.

### The current flow is:
* create an issue `glab issue create --title "" --description ""` 
* go to the web-interface to link the relevant issue.

### Possible solution:
Introduce a --linked-issue flag, that takes an issue ulr/id from the cli.

### PR DESCRIPTION
**Pull request by zemzale**
**Description**
- Add create LinkIssues api functino
- Add issue linking option

**Related Issue**
Resolves #351

**How Has This Been Tested?**
Worked on my testing repo

**Screenshots (if appropriate):**
image
image

**Types of changes**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation
- [ ] Chore (Related to CI or Packaging to platforms)

### CODE REVIEW

**Comment by zemzale** [comment]
I forgot to change the tests, don't mind the PR till then.

**Comment by zemzale** [comment]
FIxed the tests, but code coverage drops, down because I added issue linking. 
I am not sure what is the best approach for adding tests for that.

**Review by profclems — COMMENTED** [review]
Thanks for taking this on!

Do you think we should consider the `link_type` since the API allows that? 
According the API docs, the `link_type` defines the type of the relation and has 3 options: “relates_to”, “blocks”, “is_blocked_by”. The default is `relates_to`.

So here is my suggestion:
We should have a `--link-type` flag that can only be used together with `--linked-issues` flag to define the type of relation. But the default will be `relates_to`

ref: https://docs.gitlab.com/ee/api/issue_links.html#create-an-issue-link

**Comment by zemzale** [comment]
With the last commit I added the `link-type` flag. Note that any other type then `relates_to` is not gonna work unless you are on starter|bronze plan, but you are just gonna get an error 
```
POST https://gitlab.com/api/v4/projects/zemzale/test/issues/33/links: 403 {message: Blocked issues not available for current license}
```

**Review by profclems — APPROVED** [review]

**Comment by profclems** [comment]
> With the last commit I added the `link-type` flag. Note that any other type then `relates_to` is not gonna work unless you are on starter|bronze plan, but you are just gonna get an error
> 
> ```
> POST https://gitlab.com/api/v4/projects/zemzale/test/issues/33/links: 403 {message: Blocked issues not available for current license}
> ```

Noted. I think the error message is self-explanatory

**Pull request merged**
