### PR TITLE
fix(mr_create/issue_create): add encoding to title and change description encoding

### LINKED ISSUE #833: `glab mr new -w` does not escape spaces
**Description**
My default browser (LuaKit) treats a CLI argument with spaces as a search query rather than a URI.

**Expected Behavior vs Actual Behavior**
All symbols that are not allowed in a URI should be URI-encoded, though at least the spaces are preserved as-is.

**Possible Fix**

**Steps to Reproduce**

**Logs**
```
@bq:16:30:30:/media/d/temp/git/slidge$ glab mr new -w
? Choose a template Open a blank merge request
? Title: Catch the ValueError when filling a roster
? Description <Received>
Opening gitlab.com/bodqhrohro/slidge/-/merge_requests/new in your browser.
```

**Your Environment**

* Version used (Run `glab --version`): glab version 1.20.0
* Operating System and version: Debian 11

### PR DESCRIPTION
**Pull request by kartikay101**
- Prevent browsers from converting a space containing query to a search query
- Allow users to add symbols to their title and description
    - QueryEscape does not escape '+' which is converted to a space by the browser

## Description
Used path encoding to convert spaces to `%20` which prevents Titles and Descriptions with spaces from getting converted to search queries
Did not use Query Encoding as it prevents the usage of `+` which won't be encoded and thus converted to a space 

## Related Issue

Resolves #833 

## How Has This Been Tested?
Manually tested on
- firefox
- chrome
- chromium

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation
- [ ] Chore (Related to CI or Packaging to platforms)

### CODE REVIEW

**Comment by kartikay101** [comment]
Got rid of a debug statement left in the code : (

**Comment by kartikay101** [comment]
Discarded unused repo parameter

**Comment by kartikay101** [comment]
~This fix is the actual URL fix for all problems but it does not work with Mac ( the URL generated is correct but when opening with `/bin/open generated_url` another encoder runs and messes things up. Might not be worth merging until a fix for open command is found~

The issue was not with the open command, rather with the `tick` being used, removing the `utf8=tick` does not auto encode urls and everything works like a charm

**Comment by profclems** [comment]
@kartikay101 thanks for working on this! Please rebase your branch

**Comment by kartikay101** [comment]
Done

**Comment by kartikay101** [comment]
Hey I was wondering if you got a chance to look into this @profclems

**Review by zemzale — APPROVED** [review]
LGTM. Nice work @kartikay101

**Pull request merged**
