### PR TITLE
do not navigate, when we don't have jobs loaded yet.

### LINKED ISSUE #991: crash on mesa CI at gitlab.freedesktop.org
Hello! First I want you to thank you for this amazing piece of software!
Second, report of crash:

**Description**
Crash on big CI ( gitlab.freedesktop.org ). There is lot of stages/pipelines...
**Logs**
```
$ glab ci view testing-1
2022/04/27 13:50:34 runtime error: index out of range [0] with length 0
goroutine 1 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.17.5/x64/src/runtime/debug/stack.go:24 +0x65
github.com/profclems/glab/commands/ci/view.recoverPanic(0x30)
	/home/runner/work/glab/glab/commands/ci/view/view.go:546 +0x4c
panic({0xcfe8e0, 0xc000592030})
	/opt/hostedtoolcache/go/1.17.5/x64/src/runtime/panic.go:1038 +0x215
github.com/rivo/tview.(*Application).Run.func1()
	/home/runner/go/pkg/mod/github.com/rivo/tview@v0.0.0-20211029142923-a4acb08f513e/application.go:243 +0x4d
panic({0xcfe8e0, 0xc000592030})
	/opt/hostedtoolcache/go/1.17.5/x64/src/runtime/panic.go:1038 +0x215
github.com/profclems/glab/commands/ci/view.(*navigator).Navigate(0x0, {0x0, 0xc00062f7e8, 0x444a93}, 0x436036)
	/home/runner/work/glab/glab/commands/ci/view/view.go:299 +0x1ed
github.com/profclems/glab/commands/ci/view.inputCapture.func1(0xc0007cc0c0)
	/home/runner/work/glab/glab/commands/ci/view/view.go:164 +0x1d3
github.com/rivo/tview.(*Application).Run(0xc000642000)
	/home/runner/go/pkg/mod/github.com/rivo/tview@v0.0.0-20211029142923-a4acb08f513e/application.go:318 +0x782
github.com/profclems/glab/commands/ci/view.drawView({{0x7fffbb53342b, 0x9}, {0xc000517990, 0xa}, 0xc000134380, {0xc000024180, 0x28}, 0xc000522e00, {0xf5af60, 0xc00000e018}})
	/home/runner/work/glab/glab/commands/ci/view/view.go:135 +0x6a6
github.com/profclems/glab/commands/ci/view.NewCmdView.func1(0xc0004c3400, {0xc00059d6b0, 0x1, 0x1})
	/home/runner/work/glab/glab/commands/ci/view/view.go:98 +0x1fa
github.com/spf13/cobra.(*Command).execute(0xc0004c3400, {0xc00059d690, 0x1, 0x1})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc0005ac280)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
main.main()
	/home/runner/work/glab/glab/cmd/glab/main.go:147 +0x90c
```

**Your Environment**
x86_64, GNOME
* Version used (Run `glab --version`):
glab version 1.22.0 (2022-01-10)

* Operating System and version:
Debian unstable/testing

### PR DESCRIPTION
**Pull request by okias**
## Description
Catch out-of-bound exception
## Related Issue

Resolves https://github.com/profclems/glab/issues/991

## How Has This Been Tested?
Runtime tested, on linux, amd64

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation
- [ ] Chore (Related to CI or Packaging to platforms)

### CODE REVIEW

**Comment by okias** [comment]
Would be nice to have something like "Loading the pipeline..." or something informative on screen. what do you people think?

**Comment by okias** [comment]
not stale, please merge. Also DeepSource: Go seems to noticed unrelated issues(?)

**Comment by profclems** [comment]
Hi @okias, thanks a lot for this PR. I love this, however, we announced that this project is officially adopted by GitLab https://github.com/profclems/glab/issues/983#issue-1175723125. All new contributions should be made to the GitLab repo: https://gitlab.com/gitlab-org/cli

**Comment by okias** [comment]
@profclems thanks, moved to https://gitlab.com/gitlab-org/cli/-/merge_requests/1012

**Pull request closed without merging**
