### PR TITLE
feat(repo): Create project from URL

### LINKED ISSUE #618: the project create command currently does not support full urls as parameter
**Describe the feature or problem you'd like to solve**
the project create command currently does not support full urls as parameter

**Propose a Solution**
Allow for it

**Additional context**
https://github.com/profclems/glab/issues/609#issuecomment-779973378

Additionally, would any of the settings in the config file allow for overwriting the default host setting?

### PR DESCRIPTION
**Pull request by zemzale**
**Description**
This is gonna allow for creating projects using full URL which is gonna
override the host URL too.

The command doesn't have unit tests and probably should be refactored, so I opened issue about that #708

**Related Issue**
Resolves #618

**How Has This Been Tested?**
Locally tested

**Types of changes**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation
- [ ] Chore (Related to CI or Packaging to platforms)

### CODE REVIEW

**Review by profclems — CHANGES_REQUESTED** [review]
Thanks for working on this @zemzale.

I tested this and got a few issues
- This works fine when the argument provided is a URL (https://gitlab.com/profclems/test)
- Does not support ssh urls (e.g. git@gitlab.com:profclems/test.git)
- Does not support urls with `.git` prefix (https://gitlab.com/profclems/test.git)
- It disregards the hostname and uses the default host `gitlab.com`

**Comment by zemzale** [comment]
Indeed these cases wont work. I will fix these issues, shouldn't be too hard, I just didn't have the chance to test against a private instance.

**Comment by profclems** [comment]
I think it should be easier with this function in the [`glrepo`](https://github.com/profclems/glab/blob/a17c5625128cdcad0dcb430df633b91ea7f379b6/internal/glrepo/repo.go) package

https://github.com/profclems/glab/blob/a17c5625128cdcad0dcb430df633b91ea7f379b6/internal/glrepo/repo.go#L117-L183

**Comment by profclems** [comment]
@zemzale I just pushed a commit to fix the issues I listed

**Review by profclems — APPROVED** [review]

**Pull request merged**
